@echo off
echo Resetting TCP/IP stack...
netsh int ip reset
echo Flushing DNS resolver cache...
ipconfig /flushdns
echo Releasing and renewing DHCP lease...
ipconfig /release
ipconfig /renew
echo Resetting Winsock...
netsh winsock reset
echo Clearing ARP cache...
arp -d
echo Network configuration reset complete.